
const rows=DATA;
const welcome=document.querySelector('.welcome'),articles=[...document.querySelectorAll('.reader')],sidebar=document.querySelector('.sidebar'),menu=document.getElementById('mobile-menu'),q=document.getElementById('query'),stage=document.getElementById('stage');
let current='',toastTimer,printOpen=[],printing=false;
function filter(){const term=q.value.trim().toLowerCase();const found=rows.filter(r=>(stage.value==='0'||r.stage===stage.value)&&[r.id,r.title,r.method,r.prompt,r.stop,r.follow,r.verify].join(' ').toLowerCase().includes(term));const ids=new Set(found.map(r=>r.id));document.querySelectorAll('[data-id]').forEach(link=>link.hidden=!ids.has(link.dataset.id));document.querySelectorAll('[data-group]').forEach(group=>group.hidden=!found.some(r=>r.stage===group.dataset.group));document.getElementById('count').textContent=found.length+' 題';document.getElementById('rail-empty').hidden=found.length>0;document.getElementById('catalog-empty').hidden=found.length>0;}
function route(focus=false){const raw=location.hash.slice(1),id=raw.startsWith('q-')?raw.slice(2):'';const selected=rows.find(r=>r.id===id);current=selected?id:'';welcome.hidden=!!selected;articles.forEach(a=>a.hidden=a.id!=='q-'+current);document.querySelectorAll('.question-link').forEach(link=>{const active=link.dataset.id===current;link.classList.toggle('active',active);if(active)link.setAttribute('aria-current','page');else link.removeAttribute('aria-current');});document.getElementById('mobile-label').textContent=selected?selected.id+' · '+selected.title:'找題目 · 19 題解題筆記';document.title=selected?selected.id+' '+selected.title+' · 解題筆記':'解題筆記 · AI賦能會計';sidebar.classList.remove('expanded');menu.setAttribute('aria-expanded','false');if(selected){const a=document.getElementById('q-'+id);if(focus)a.focus({preventScroll:true});window.scrollTo({top:0,behavior:'instant'});}else if(raw==='methods'){requestAnimationFrame(()=>document.getElementById('methods').scrollIntoView({behavior:'instant'}));}else if(focus){window.scrollTo({top:0,behavior:'instant'});}}
menu.addEventListener('click',()=>{const expanded=sidebar.classList.toggle('expanded');menu.setAttribute('aria-expanded',String(expanded));});q.addEventListener('input',filter);stage.addEventListener('change',filter);document.getElementById('clear').addEventListener('click',()=>{q.value='';stage.value='0';filter();});window.addEventListener('hashchange',()=>route(true));
function toast(message){const t=document.getElementById('toast');t.textContent=message;t.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.hidden=true,4500);}
document.querySelectorAll('.copy').forEach(button=>button.addEventListener('click',async()=>{const text=rows.find(r=>r.id===button.dataset.copy).prompt;button.disabled=true;try{if(navigator.clipboard&&window.isSecureContext){await navigator.clipboard.writeText(text);}else{const area=document.createElement('textarea');area.value=text;area.style.position='fixed';area.style.top='0';area.style.opacity='0';document.body.append(area);area.select();const ok=document.execCommand('copy');area.remove();if(!ok)throw Error('copy failed');}toast('提示詞已複製。貼給 AI 前，記得換成你的資料與日期。');}catch(e){const range=document.createRange();range.selectNodeContents(document.getElementById('prompt-'+button.dataset.copy));const selection=window.getSelection();selection.removeAllRanges();selection.addRange(range);toast('已選取提示詞；請用複製指令，或長按文字複製。');}finally{button.disabled=false;button.focus({preventScroll:true});}}));
window.addEventListener('beforeprint',()=>{if(printing)return;printing=true;printOpen=[...document.querySelectorAll('.verify')].map(d=>d.open);document.querySelectorAll('.verify').forEach(d=>d.open=true);});window.addEventListener('afterprint',()=>{if(!printing)return;document.querySelectorAll('.verify').forEach((d,i)=>d.open=printOpen[i]);printing=false;});filter();route();
